<?php
/**
 * Copyright © Intenso Commerce. All rights reserved.
 * See License.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $url = $block->getReviewsUrl() . '#reviews'; ?>
<?php $urlForm = $block->getReviewsUrl() . '#review-form'; ?>
<?php if ($block->getReviewsCount()): ?>
<?php $rating = $block->getRatingSummary(); ?>
<div class="product-reviews-summary<?= !$rating ? ' no-rating' : ''?>" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
    <?php if ($rating):?>
    <div class="rating-summary<?= ($block->displaySummaryPopover()) ? ' summary-popover' : ''; ?>"
        data-review-product="<?= $block->getProduct()->getId()?>"
        data-review-url="<?= $block->getSummaryUrl($block->getProduct()->getId())?>">
         <span class="label"><span><?= /* @escapeNotVerified */ __('Rating') ?>:</span></span>
         <div class="rating-result" title="<?= /* @escapeNotVerified */ $rating; ?>%">
             <span style="width:<?= /* @escapeNotVerified */ $rating; ?>%"><span><span itemprop="ratingValue"><?= /* @escapeNotVerified */ $rating; ?></span>% of <span itemprop="bestRating">100</span></span></span>
             <?php if ($block->displaySummaryPopover()): ?>
             <div class="summary-popover-content">
                 <div class="review-popover">
                     <div class="loader">
                         <img src="<?= $block->getViewFileUrl('Intenso_Review::images/loader.gif'); ?>"
                  alt="<?= /* @escapeNotVerified */ __('Loading...') ?>">
                     </div>
                 </div>
             </div>
             <?php endif; ?>
         </div>
         <?php if ($block->displaySummaryPopover()): ?>
         <div class="summary-popover-corner"></div>
         <?php endif;?>
    </div>
    <?php endif;?>
    <div class="reviews-actions">
        <a class="action view" href="<?= /* @escapeNotVerified */ $url ?>"><span itemprop="reviewCount"><?= /* @escapeNotVerified */ $block->getReviewsCount() ?></span>&nbsp;<span><?= /* @escapeNotVerified */ ($block->getReviewsCount() == 1) ? __('Review') : __('Reviews') ?></span></a>
        <a class="action add intenso-add-your-review-link" href="<?= /* @escapeNotVerified */ $urlForm ?>"><?= /* @escapeNotVerified */ __('Add Your Review') ?></a>
    </div>
</div>
<?php elseif ($block->getDisplayIfEmpty()): ?>
<div class="product-reviews-summary empty">
    <div class="reviews-actions">
        <a class="action add intenso-add-your-review-link" href="<?= /* @escapeNotVerified */ $urlForm; ?>">
            <?= /* @escapeNotVerified */ __('Be the first to review this product') ?>
        </a>
    </div>
</div>
<?php endif; ?>
