<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var  $block \Magento\Sales\Block\Order\View*/?>
<?php
	$_orderDateInitial = $block->getOrder()->getCreatedAt();
	$_orderDate = date("Y-m-d H:i:s", strtotime('+9 hours', strtotime($_orderDateInitial)));
	$year = date('Y', strtotime($_orderDate));
	$month = date('m', strtotime($_orderDate));
	$day = date('d', strtotime($_orderDate));
	$time = date('H', strtotime($_orderDate));
	$minute = date('i', strtotime($_orderDate));
	$second = date('s', strtotime($_orderDate));


?>
注文日時：<?=$year?>年<?=$month?>月<?=$day?>日 <?=$time?>時<?=$minute?>分<?=$second?>秒