<?php /** @var \Veriteworks\Gmo\Block\Info\Cvs $block */?>
<p><strong><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></strong></p>
<?php if ($_specificInfo = $block->getSpecificInformation()):?>
    <table>
        <?php foreach ($_specificInfo as $_label => $_value):?>
            <tr>
                <td><?= $block->escapeHtml($_label)?>:</td>
            <?php if ($_label == __('Receipt URL')->__toString()):?>
                <td>
                    <a href="<?=$block->escapeHtmlAttr($_value)?>"
                       target="_blank"><?=$block->escapeHtml(__('Go to payment page'))?></a>
                </td>
            <?php else:?>
                <td><?= $block->escapeHtml($_value); ?></td>
            <?php endif;?>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>

<?= $block->getChildHtml()?>
