<?php
/**
 * @var \Magento\Payment\Block\Transparent\Form $block
 */
$code = $block->escapeHtml($block->getMethodCode());
$cvsType = $block->getInfoData('cvs_type');
?>
<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?= $block->escapeHtmlAttr($code); ?>" style="display: none;">
    <div class="field-type admin__field _required">
        <label for="<?= $block->escapeHtmlAttr($code); ?>_cvs_type" class="admin__field-label">
            <span><?= $block->escapeHtml(__('CVS Name')); ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= $block->escapeHtmlAttr($code); ?>_cvs_type"
                    name="payment[cvs_type]" data-validate='{
                        required:true
                    }'
                    class="select">
                <option value=""><?= $block->escapeHtml(__('--Please Select--')); ?></option>
                <?php foreach ($block->getCvsAvailableTypes() as $typeCode => $typeName): ?>
                    <option value="<?= $block->escapeHtml($typeCode); ?>"
                        <?php if ($typeCode == $cvsType):
                            ?> selected="selected"<?php
                        endif; ?>>
                        <?= $block->escapeHtml($typeName); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <?= $block->getChildHtml() ?>
</fieldset>
